In [1]:
import pandas as pd
import numpy as np

In [3]:
datas = pd.date_range('20180101', periods=60, freq="D")
df = pd.DataFrame(np.random.randn(60,5), index=datas, columns=list("ABCDE"))

In [4]:
# informa a dimensão do dataframe
df

                   A         B         C         D         E
2018-01-01  0.160477 -0.524794 -0.125292  0.382242  0.134846
2018-01-02  1.513953  0.444050  0.410485 -0.270246  0.398213
2018-01-03 -0.574713 -0.611776 -0.063722 -0.593155 -0.780186
2018-01-04 -2.695573 -0.987037  0.972583  0.190592  0.735547
2018-01-05 -0.547554 -1.666080  0.242483 -1.050019 -2.080544
2018-01-06  0.061711 -1.121109  1.188028  0.826946  0.598361
2018-01-07  0.178521  0.612424  0.947850 -1.093393  0.104596
2018-01-08  0.672328  0.189943  1.240527  1.133248 -0.331447
2018-01-09  0.796195 -0.491610 -0.939700  0.789883 -1.450196
2018-01-10 -0.952385 -0.633134  1.166880 -0.028172  0.355878
2018-01-11  0.612444 -0.422526  1.047414 -0.888996 -0.357145
2018-01-12 -2.151719 -0.294887 -3.189259  1.698927 -0.466726
2018-01-13 -1.276977 -0.737328  0.313077 -0.112889  0.527252
2018-01-14 -1.052414 -0.437671 -0.437019 -0.330027  0.603090
2018-01-15  0.294733  1.117483  0.607397  0.034551  1.247690
2018-01-16 -0.730635  0.397921 -0.096329 -1.171317  2.185375
2018-01-17 -1.367690 -0.210936  0.287858  0.300595  1.594287
2018-01-18  0.569180 -0.655238 -0.638144 -0.528038 -0.538499
2018-01-19  0.549965 -0.590823  0.129360  1.242747 -0.043824
2018-01-20 -1.833710 -0.495046 -0.701029  1.408417 -1.156287
2018-01-21 -0.245210 -0.242731  1.105143 -0.412471 -0.375565
2018-01-22 -0.186453  0.119004 -0.704758 -0.793346  0.264477
2018-01-23  0.826599 -0.567588  1.039983 -0.481244  0.258831
2018-01-24 -0.424968 -1.275804 -1.863905 -1.664693 -0.658378
2018-01-25 -1.310179 -1.551286  0.531684 -0.858128  0.475943
2018-01-26 -1.082774  0.588841 -0.793789 -0.980748 -0.193255
2018-01-27 -1.119019 -1.050205  1.130617  0.362963 -0.971454
2018-01-28  2.065038 -0.971747  1.030693 -0.029396  0.319736
2018-01-29 -0.932001  0.094545 -1.231188  0.513543  1.141094
2018-01-30  1.375457  1.225593  0.837796  1.278304 -0.760443
2018-01-31  1.154966  0.859609 -0.374080 -0.395711 -0.524731
2018-02-01 -2.054807  0.568346 -0.625836 -0.455920  1.186394
2018-02-02 -1.999693 -0.333094 -0.139245  0.743573 -0.685273
2018-02-03 -0.235755 -0.781309 -0.346941  0.788218 -0.131431
2018-02-04  0.092686 -0.219254  1.038685  0.024490  0.279001
2018-02-05 -0.338504  0.650457  0.956466  0.179297 -0.430564
2018-02-06  0.809993  1.367606 -0.023041 -0.951281 -0.485615
2018-02-07 -0.810980 -0.732109 -0.054211  0.015749  0.625604
2018-02-08  0.221125 -0.315408  1.418289 -0.443299 -1.902368
2018-02-09 -1.139068 -0.221817 -0.473572  0.532499 -1.539145
2018-02-10  0.995803  1.996399 -1.205481  0.531096 -0.014008
2018-02-11 -0.323105 -0.487384  0.286622  0.260878  0.081750
2018-02-12  0.146574 -0.044077  0.021274  0.031582 -1.111023
2018-02-13 -0.166381  0.241097 -1.666309 -1.254385  0.598561
2018-02-14 -1.565783  0.492380  0.068521 -0.946657  1.756331
2018-02-15  0.505462 -0.776756 -0.206947 -0.548574  0.113158
2018-02-16  0.090496 -0.576843 -1.074970  0.685245  0.839153
2018-02-17 -2.198775  0.136610  1.782977  0.500324 -0.592202
2018-02-18  1.048702  0.130400 -1.708389 -0.077568 -1.244438
2018-02-19  1.222166 -0.110467  0.646867  0.060606 -0.371477
2018-02-20 -0.465449 -0.099163 -0.671150  0.905553 -1.501724
2018-02-21 -0.369285  0.742085 -0.456534 -1.356754  0.154112
2018-02-22  0.128981  0.092170 -0.515910  0.480724  1.336306
2018-02-23  0.081976 -0.194670 -2.337646  0.400070  0.202559
2018-02-24 -1.420064  0.933436 -0.700841  0.232903 -1.589482
2018-02-25  2.799857  0.733131  0.537505 -1.379599 -2.308291
2018-02-26  0.819124 -0.526282  0.060694 -1.418674 -1.886958
2018-02-27 -0.439674 -1.043928 -0.813396  0.322749  0.368083
2018-02-28  0.975864 -0.771620  0.198753  0.818318  0.746940
2018-03-01  2.780009 -0.758351  1.087544 -0.283351 -1.955951

In [5]:
df.shape

(60, 5)

In [6]:
df.head()

                   A         B         C         D         E
2018-01-01  0.160477 -0.524794 -0.125292  0.382242  0.134846
2018-01-02  1.513953  0.444050  0.410485 -0.270246  0.398213
2018-01-03 -0.574713 -0.611776 -0.063722 -0.593155 -0.780186
2018-01-04 -2.695573 -0.987037  0.972583  0.190592  0.735547
2018-01-05 -0.547554 -1.666080  0.242483 -1.050019 -2.080544

In [7]:
df['F'] = 1

In [8]:
df.head(10)

                   A         B         C         D         E  F
2018-01-01  0.160477 -0.524794 -0.125292  0.382242  0.134846  1
2018-01-02  1.513953  0.444050  0.410485 -0.270246  0.398213  1
2018-01-03 -0.574713 -0.611776 -0.063722 -0.593155 -0.780186  1
2018-01-04 -2.695573 -0.987037  0.972583  0.190592  0.735547  1
2018-01-05 -0.547554 -1.666080  0.242483 -1.050019 -2.080544  1
2018-01-06  0.061711 -1.121109  1.188028  0.826946  0.598361  1
2018-01-07  0.178521  0.612424  0.947850 -1.093393  0.104596  1
2018-01-08  0.672328  0.189943  1.240527  1.133248 -0.331447  1
2018-01-09  0.796195 -0.491610 -0.939700  0.789883 -1.450196  1
2018-01-10 -0.952385 -0.633134  1.166880 -0.028172  0.355878  1

In [9]:
df['G'] = range(60)

In [11]:
df.head(10)

                   A         B         C         D         E  F  G
2018-01-01  0.160477 -0.524794 -0.125292  0.382242  0.134846  1  0
2018-01-02  1.513953  0.444050  0.410485 -0.270246  0.398213  1  1
2018-01-03 -0.574713 -0.611776 -0.063722 -0.593155 -0.780186  1  2
2018-01-04 -2.695573 -0.987037  0.972583  0.190592  0.735547  1  3
2018-01-05 -0.547554 -1.666080  0.242483 -1.050019 -2.080544  1  4
2018-01-06  0.061711 -1.121109  1.188028  0.826946  0.598361  1  5
2018-01-07  0.178521  0.612424  0.947850 -1.093393  0.104596  1  6
2018-01-08  0.672328  0.189943  1.240527  1.133248 -0.331447  1  7
2018-01-09  0.796195 -0.491610 -0.939700  0.789883 -1.450196  1  8
2018-01-10 -0.952385 -0.633134  1.166880 -0.028172  0.355878  1  9

In [12]:
df['Produto'] = df['A'] * df['B']

In [13]:
df

                   A         B         C         D         E  F   G   Produto
2018-01-01  0.160477 -0.524794 -0.125292  0.382242  0.134846  1   0 -0.084217
2018-01-02  1.513953  0.444050  0.410485 -0.270246  0.398213  1   1  0.672271
2018-01-03 -0.574713 -0.611776 -0.063722 -0.593155 -0.780186  1   2  0.351595
2018-01-04 -2.695573 -0.987037  0.972583  0.190592  0.735547  1   3  2.660631
2018-01-05 -0.547554 -1.666080  0.242483 -1.050019 -2.080544  1   4  0.912269
2018-01-06  0.061711 -1.121109  1.188028  0.826946  0.598361  1   5 -0.069185
2018-01-07  0.178521  0.612424  0.947850 -1.093393  0.104596  1   6  0.109331
2018-01-08  0.672328  0.189943  1.240527  1.133248 -0.331447  1   7  0.127704
2018-01-09  0.796195 -0.491610 -0.939700  0.789883 -1.450196  1   8 -0.391418
2018-01-10 -0.952385 -0.633134  1.166880 -0.028172  0.355878  1   9  0.602987
2018-01-11  0.612444 -0.422526  1.047414 -0.888996 -0.357145  1  10 -0.258774
2018-01-12 -2.151719 -0.294887 -3.189259  1.698927 -0.466726  1  11  0.634514
2018-01-13 -1.276977 -0.737328  0.313077 -0.112889  0.527252  1  12  0.941551
2018-01-14 -1.052414 -0.437671 -0.437019 -0.330027  0.603090  1  13  0.460612
2018-01-15  0.294733  1.117483  0.607397  0.034551  1.247690  1  14  0.329359
2018-01-16 -0.730635  0.397921 -0.096329 -1.171317  2.185375  1  15 -0.290735
2018-01-17 -1.367690 -0.210936  0.287858  0.300595  1.594287  1  16  0.288495
2018-01-18  0.569180 -0.655238 -0.638144 -0.528038 -0.538499  1  17 -0.372948
2018-01-19  0.549965 -0.590823  0.129360  1.242747 -0.043824  1  18 -0.324932
2018-01-20 -1.833710 -0.495046 -0.701029  1.408417 -1.156287  1  19  0.907771
2018-01-21 -0.245210 -0.242731  1.105143 -0.412471 -0.375565  1  20  0.059520
2018-01-22 -0.186453  0.119004 -0.704758 -0.793346  0.264477  1  21 -0.022189
2018-01-23  0.826599 -0.567588  1.039983 -0.481244  0.258831  1  22 -0.469168
2018-01-24 -0.424968 -1.275804 -1.863905 -1.664693 -0.658378  1  23  0.542176
2018-01-25 -1.310179 -1.551286  0.531684 -0.858128  0.475943  1  24  2.032462
2018-01-26 -1.082774  0.588841 -0.793789 -0.980748 -0.193255  1  25 -0.637582
2018-01-27 -1.119019 -1.050205  1.130617  0.362963 -0.971454  1  26  1.175199
2018-01-28  2.065038 -0.971747  1.030693 -0.029396  0.319736  1  27 -2.006694
2018-01-29 -0.932001  0.094545 -1.231188  0.513543  1.141094  1  28 -0.088116
2018-01-30  1.375457  1.225593  0.837796  1.278304 -0.760443  1  29  1.685751
2018-01-31  1.154966  0.859609 -0.374080 -0.395711 -0.524731  1  30  0.992819
2018-02-01 -2.054807  0.568346 -0.625836 -0.455920  1.186394  1  31 -1.167842
2018-02-02 -1.999693 -0.333094 -0.139245  0.743573 -0.685273  1  32  0.666085
2018-02-03 -0.235755 -0.781309 -0.346941  0.788218 -0.131431  1  33  0.184197
2018-02-04  0.092686 -0.219254  1.038685  0.024490  0.279001  1  34 -0.020322
2018-02-05 -0.338504  0.650457  0.956466  0.179297 -0.430564  1  35 -0.220182
2018-02-06  0.809993  1.367606 -0.023041 -0.951281 -0.485615  1  36  1.107752
2018-02-07 -0.810980 -0.732109 -0.054211  0.015749  0.625604  1  37  0.593726
2018-02-08  0.221125 -0.315408  1.418289 -0.443299 -1.902368  1  38 -0.069744
2018-02-09 -1.139068 -0.221817 -0.473572  0.532499 -1.539145  1  39  0.252665
2018-02-10  0.995803  1.996399 -1.205481  0.531096 -0.014008  1  40  1.988020
2018-02-11 -0.323105 -0.487384  0.286622  0.260878  0.081750  1  41  0.157476
2018-02-12  0.146574 -0.044077  0.021274  0.031582 -1.111023  1  42 -0.006461
2018-02-13 -0.166381  0.241097 -1.666309 -1.254385  0.598561  1  43 -0.040114
2018-02-14 -1.565783  0.492380  0.068521 -0.946657  1.756331  1  44 -0.770961
2018-02-15  0.505462 -0.776756 -0.206947 -0.548574  0.113158  1  45 -0.392621
2018-02-16  0.090496 -0.576843 -1.074970  0.685245  0.839153  1  46 -0.052202
2018-02-17 -2.198775  0.136610  1.782977  0.500324 -0.592202  1  47 -0.300374
2018-02-18  1.048702  0.130400 -1.708389 -0.077568 -1.244438  1  48  0.136751
2018-02-19  1.222166 -0.110467  0.646867  0.060606 -0.371477  1  49 -0.135009
2018-02-20 -0.465449 -0.099163 -0.671150  0.905553 -1.501724  1  50  0.046155
2018-02-21 -0.369285  0.742085 -0.456534 -1.356754  0.154112  1  51 -0.274041
2018-02-22  0.128981  0.092170 -0.515910  0.480724  1.336306  1  52  0.011888
2018-02-23  0.081976 -0.194670 -2.337646  0.400070  0.202559  1  53 -0.015958
2018-02-24 -1.420064  0.933436 -0.700841  0.232903 -1.589482  1  54 -1.325539
2018-02-25  2.799857  0.733131  0.537505 -1.379599 -2.308291  1  55  2.052663
2018-02-26  0.819124 -0.526282  0.060694 -1.418674 -1.886958  1  56 -0.431090
2018-02-27 -0.439674 -1.043928 -0.813396  0.322749  0.368083  1  57  0.458988
2018-02-28  0.975864 -0.771620  0.198753  0.818318  0.746940  1  58 -0.752996
2018-03-01  2.780009 -0.758351  1.087544 -0.283351 -1.955951  1  59 -2.108221

In [14]:
df['D'] = 88

In [15]:
df.head(10)

                   A         B         C   D         E  F  G   Produto
2018-01-01  0.160477 -0.524794 -0.125292  88  0.134846  1  0 -0.084217
2018-01-02  1.513953  0.444050  0.410485  88  0.398213  1  1  0.672271
2018-01-03 -0.574713 -0.611776 -0.063722  88 -0.780186  1  2  0.351595
2018-01-04 -2.695573 -0.987037  0.972583  88  0.735547  1  3  2.660631
2018-01-05 -0.547554 -1.666080  0.242483  88 -2.080544  1  4  0.912269
2018-01-06  0.061711 -1.121109  1.188028  88  0.598361  1  5 -0.069185
2018-01-07  0.178521  0.612424  0.947850  88  0.104596  1  6  0.109331
2018-01-08  0.672328  0.189943  1.240527  88 -0.331447  1  7  0.127704
2018-01-09  0.796195 -0.491610 -0.939700  88 -1.450196  1  8 -0.391418
2018-01-10 -0.952385 -0.633134  1.166880  88  0.355878  1  9  0.602987